name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # Trigger when pushing to main branch
  pull_request:
    branches:
      - main   # Also trigger on PRs to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step  2: Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build and run tests
      - name: Build and test with Maven
        run: mvn clean verify
        env:
          JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
          JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}



      # Step 4: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 5: Build Docker image
      - name: Build Docker image
        run: docker build -t yukijanse/springboot-social-media-api:latest .
        env:
          JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
          JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}


      # Step 6: Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push yukijanse/springboot-social-media-api:latest
